# Generated by Django 5.0.1 on 2024-01-24 21:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_remove_bid_bidder_remove_bid_listing_bid_bidder_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='createdAt',
            field=models.DateTimeField(default=datetime.datetime(2024, 1, 24, 21, 41, 44, 590960, tzinfo=datetime.timezone.utc)),
        ),
    ]
