# Generated by Django 5.0.1 on 2024-01-24 21:42

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_auctionlisting_createdat'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='createdAt',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
