# Generated by Django 5.0.1 on 2024-01-26 20:21

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_alter_auctionlisting_createdat'),
    ]

    operations = [
        migrations.AddField(
            model_name='auctionlisting',
            name='users_watching',
            field=models.ManyToManyField(blank=True, related_name='watchlistItems', to=settings.AUTH_USER_MODEL),
        ),
    ]
