# Generated by Django 4.2.9 on 2024-01-29 17:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0013_auctionlisting_active_auctionlisting_winner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auctionlisting',
            name='winner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='AuctionsWon', to=settings.AUTH_USER_MODEL),
        ),
    ]
